import { createClient } from "@supabase/supabase-js"

export default createClient('https://rqumerxnwmqfikvpjbph.supabase.co', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxdW1lcnhud21xZmlrdnBqYnBoIiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODg0MTM1MTMsImV4cCI6MjAwMzk4OTUxM30.bAYd8sIbl6SbdYdP-YeFg5ut_k3quGryPPzH9Msc7Z0')